import { ITest } from '../models/xample-dashboard.models';

export const DATA: ITest[] = [
  {
    first_name: 'Rafi',
    last_name: 'Pratama',
    full_name: 'Rafi Pratama',
    email: 'rafi.pratama@example.com',
    age: 27,
    street: 'Jl. Merpati No. 12',
    city: 'Bandung',
    province: 'Jawa Barat',
    nation: 'Indonesia',
    postal_code: '40212',
    job_title: 'Frontend Developer',
    company_name: 'TechNova',
    company_address: 'Jl. Dipatiukur No. 45, Bandung',
    work_email: 'rafi.pratama@technova.com',
  },
  {
    first_name: 'Aulia',
    last_name: 'Rahmadani',
    full_name: 'Aulia Rahmadani',
    email: 'aulia.rahmadani@example.com',
    age: 24,
    street: 'Jl. Kenanga No. 7',
    city: 'Jakarta',
    province: 'DKI Jakarta',
    nation: 'Indonesia',
    postal_code: '12560',
    job_title: 'UI/UX Designer',
    company_name: 'PixelCraft',
    company_address: 'Jl. Sudirman No. 88, Jakarta',
    work_email: 'aulia.rahmadani@pixelcraft.co',
  },
  {
    first_name: 'Dimas',
    last_name: 'Wardhana',
    full_name: 'Dimas Wardhana',
    email: 'dimas.wardhana@example.com',
    age: 30,
    street: 'Jl. Anggrek No. 19',
    city: 'Surabaya',
    province: 'Jawa Timur',
    nation: 'Indonesia',
    postal_code: '60123',
    job_title: 'Backend Engineer',
    company_name: 'ServerForge',
    company_address: 'Jl. Ahmad Yani No. 99, Surabaya',
    work_email: 'dimas.wardhana@serverforge.id',
  },
  {
    first_name: 'Nadia',
    last_name: 'Putri',
    full_name: 'Nadia Putri',
    email: 'nadia.putri@example.com',
    age: 26,
    street: 'Jl. Dahlia No. 3',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    nation: 'Indonesia',
    postal_code: '55281',
    job_title: 'Data Analyst',
    company_name: 'Insightify',
    company_address: 'Jl. Malioboro No. 10, Yogyakarta',
    work_email: 'nadia.putri@insightify.com',
  },
  {
    first_name: 'Bagas',
    last_name: 'Saputra',
    full_name: 'Bagas Saputra',
    email: 'bagas.saputra@example.com',
    age: 28,
    street: 'Jl. Melati No. 22',
    city: 'Semarang',
    province: 'Jawa Tengah',
    nation: 'Indonesia',
    postal_code: '50148',
    job_title: 'Mobile Developer',
    company_name: 'AppWorks',
    company_address: 'Jl. Pemuda No. 40, Semarang',
    work_email: 'bagas.saputra@appworks.dev',
  },
  {
    first_name: 'Sinta',
    last_name: 'Dharma',
    full_name: 'Sinta Dharma',
    email: 'sinta.dharma@example.com',
    age: 32,
    street: 'Jl. Teratai No. 8',
    city: 'Denpasar',
    province: 'Bali',
    nation: 'Indonesia',
    postal_code: '80227',
    job_title: 'Project Manager',
    company_name: 'BaliSoft',
    company_address: 'Jl. Gatot Subroto No. 5, Denpasar',
    work_email: 'sinta.dharma@balisoft.co.id',
  },
  {
    first_name: 'Fikri',
    last_name: 'Santoso',
    full_name: 'Fikri Santoso',
    email: 'fikri.santoso@example.com',
    age: 25,
    street: 'Jl. Mawar No. 17',
    city: 'Malang',
    province: 'Jawa Timur',
    nation: 'Indonesia',
    postal_code: '65112',
    job_title: 'QA Engineer',
    company_name: 'TestLab',
    company_address: 'Jl. Veteran No. 21, Malang',
    work_email: 'fikri.santoso@testlab.id',
  },
  {
    first_name: 'Tania',
    last_name: 'Wijaya',
    full_name: 'Tania Wijaya',
    email: 'tania.wijaya@example.com',
    age: 29,
    street: 'Jl. Flamboyan No. 6',
    city: 'Makassar',
    province: 'Sulawesi Selatan',
    nation: 'Indonesia',
    postal_code: '90134',
    job_title: 'Marketing Specialist',
    company_name: 'BrandSphere',
    company_address: 'Jl. Urip Sumoharjo No. 98, Makassar',
    work_email: 'tania.wijaya@brandsphere.com',
  },
  {
    first_name: 'Kevin',
    last_name: 'Jonathan',
    full_name: 'Kevin Jonathan',
    email: 'kevin.jonathan@example.com',
    age: 31,
    street: 'Jl. Cemara No. 5',
    city: 'Medan',
    province: 'Sumatera Utara',
    nation: 'Indonesia',
    postal_code: '20151',
    job_title: 'DevOps Engineer',
    company_name: 'CloudShift',
    company_address: 'Jl. Gatot Subroto No. 12, Medan',
    work_email: 'kevin.jonathan@cloudshift.tech',
  },
  {
    first_name: 'Melani',
    last_name: 'Siregar',
    full_name: 'Melani Siregar',
    email: 'melani.siregar@example.com',
    age: 23,
    street: 'Jl. Seruni No. 11',
    city: 'Palembang',
    province: 'Sumatera Selatan',
    nation: 'Indonesia',
    postal_code: '30139',
    job_title: 'Content Writer',
    company_name: 'WriteWave',
    company_address: 'Jl. Veteran No. 77, Palembang',
    work_email: 'melani.siregar@writewave.io',
  },
];
